%
% This updates the 2018 analysis to include the *DMS data* too.
% 
%  Rhiju's HiTRACE Analysis
% /Volumes/GoogleDrive/My Drive/Projects/EteRNA_Drive/PolyA_Drive/KladwangDas_PolyA_followups/032118_For TOD report/TOD_2018/TOD S1&S7-ext1-7
% Notes & comparison data for omei and meechl, who will be using
% HiTRACE-Web.

% the sequences are the following:
%
%GGAAACCUGAAAGAUCAAAAAAAAAAAGAUCAAGUACAAAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCAAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann
%GGAAACCUGAAAGAUCUAAAAAAAAAAGAUCAAGUACUAAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext1
%GGAAACCUGAAAGAUCUUAAAAAAAAAGAUCAAGUACUUAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext2
%GGAAACCUGAAAGAUCUUUAAAAAAAAGAUCAAGUACUUUAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUCCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext3
%GGAAACCUGAAAGAUCUUUUAAAAAAAGAUCAAGUACUUUUAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext4
%GGAAACCUGAAAGAUCUUUUUAAAAAAGAUCAAGUACUUUUUAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext5
%GGAAACCUGAAAGAUCUUUUUUAAAAAGAUCAAGUACUUUUUUAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUUAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext6
%GGAAACCUGAAAGAUCUUUUUUUAAAAGAUCAAGUACUUUUUUUAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUUUACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S1-Ann-stemext7
%
%Some controls
%GGAAACCUGAAAGAUCAAAAAACAAAAGAUCAAGUACAAAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCAAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann
%GGAAACCUGAAAGAUCUAAAAACAAAAGAUCAAGUACUAAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext1
%GGAAACCUGAAAGAUCUUAAAACAAAAGAUCAAGUACUUAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext2
%GGAAACCUGAAAGAUCUUUAAACAAAAGAUCAAGUACUUUAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUCCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext3
%GGAAACCUGAAAGAUCUUUUAACAAAAGAUCAAGUACUUUUAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext4
%GGAAACCUGAAAGAUCUUUUUACAAAAGAUCAAGUACUUUUUACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext5
%GGAAACCUGAAAGAUCUUUUUUCAAAAGAUCAAGUACUUUUUUCAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGUAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext6
%GGAAACCUGAAAGAUCUUUUUUCUAAAGAUCAAGUACUUUUUUCUAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGUUACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC   S7-Ann-stemext7


% Basic setup and data readin
filenames = 'CE data';
times = [2501:5500];

% The reorder option may not be available in HiTRACE web. In that case,
% you'll have to curate the .ab1 files out of the sub-directories that
% correspond to each construct. 
% E.g., wild type (WT) is the first of 8 constructs in each subdirectory.
% There are labels on the filenames (see also the "Fig4" jpgs and pdfs)
N = 80;
reorder = [...
           1  9, 32 + [1:16:N],32+N+[1 9]...
           2 10, 32 + [2:16:N],32+N+[2 10],...
           3 11, 32 + [3:16:N],32+N+[3 11],...
           4 12, 32 + [4:16:N],32+N+[4 12],...
           5 13, 32 + [5:16:N],32+N+[5 13],...
           6 14, 32 + [6:16:N],32+N+[6 14],...
           7 15, 32 + [7:16:N],32+N+[7 15],...
           8 16, 32 + [8:16:N],32+N+[8 16],...
          17 25, 32 + [9:16:N],32+N+[17 25],...
          18 26, 32 + [10:16:N],32+N+[18 26],...
          19 27, 32 + [11:16:N],32+N+[19 27],...
          20 28, 32 + [12:16:N],32+N+[20 28],...
          21 29, 32 + [13:16:N],32+N+[21 29],...
          22 30, 32 + [14:16:N],32+N+[22 30],...
          23 31, 32 + [15:16:N],32+N+[23 31],...
          24 32, 32 + [16:16:N],32+N+[24 32],...
           ];
assert( length(reorder) == length( unique(reorder) ) ); % check that each index shows up once.

[d_all,da_all] = quick_look(filenames,times, reorder);

% save save_AllData_HiTRACE_042018_Ann_TOD_S1S7ext1-7_SSIII_RTase_StandardizationExample.mat

%setting modifier types.  Apparently the data for each modifier are
%repeated (could be non-diluted vs. diluted data)
data_type = {'nomod','SHAPE','nomod','ddATP','ddCTP','ddGTP','ddTTP','nomod','DMS'};

% Note -- these sequences are not quite what Rhiju had in his design
% documents -- Ann noticed that a 5' flanking hairpin was missing (she
% used that as a reference hairpin in all her experiments)
i = 1;
sequence{i}  = 'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCAAAAAAAAAAAGAUCAAGUACAAAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCAAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC';
structure{i} = '......((((((.....))))))...........((((...((((...........))))..((((...........))))..))))...........(((((((....)))))))..........((((((.....))))))......................';

% write out all the sequences
sequence  = {...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCAAAAAAAAAAAGAUCAAGUACAAAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCAAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUAAAAAAAAAAGAUCAAGUACUAAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUAAAAAAAAAGAUCAAGUACUUAAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUAAAAAAAAGAUCAAGUACUUUAAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUCCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUAAAAAAAGAUCAAGUACUUUUAAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUAAAAAAGAUCAAGUACUUUUUAAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUUAAAAAGAUCAAGUACUUUUUUAAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUUAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUUUAAAAGAUCAAGUACUUUUUUUAAAAGUACAACAGGAAAAAAAAAAAGCAUAGGUUCGCCUAUGCUUUUUUUACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCAAAAAACAAAAGAUCAAGUACAAAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCAAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUAAAAACAAAAGAUCAAGUACUAAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUAACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUAAAACAAAAGAUCAAGUACUUAAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUACCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUAAACAAAAGAUCAAGUACUUUAAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUCCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUAACAAAAGAUCAAGUACUUUUAACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUCAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUACAAAAGAUCAAGUACUUUUUACAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGAAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUUCAAAAGAUCAAGUACUUUUUUCAAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGUAACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    'GGAAAAGGCGUCGAGUAGACGCCAACAACGGAAACCUGAAAGAUCUUUUUUCUAAAGAUCAAGUACUUUUUUCUAAAGUACAACAGGAAAAAACAAAAGCAUAGGUUCGCCUAUGCUUUUGUUACCGUCAGCGAGUAGCUGACAAAAAGAAACAACAACAACAAC',...
    };

structure = {...
    '......((((((.....))))))...........((((...((((...........))))..((((...........))))..))))...........(((((((....)))))))..........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((.........)))))..(((((.........)))))..))))..........((((((((....)))))))).........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((.......))))))..((((((.......))))))..)))).........(((((((((....)))))))))........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((.....)))))))..(((((((.....)))))))..))))........((((((((((....)))))))))).......((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((((...))))))))..((((((((...))))))))..)))).......(((((((((((....)))))))))))......((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((((.)))))))))..(((((((((.)))))))))..))))......((((((((((((....)))))))))))).....((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((((.)))))))))..(((((((((.)))))))))..)))).....(((((((((((((....)))))))))))))....((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((((...))))))))..((((((((...))))))))..))))....((((((((((((((....))))))))))))))...((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((...........))))..((((...........))))..))))...........(((((((....)))))))..........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((.........)))))..(((((.........)))))..))))..........((((((((....)))))))).........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((.......))))))..((((((.......))))))..)))).........(((((((((....)))))))))........((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((.....)))))))..(((((((.....)))))))..))))........((((((((((....)))))))))).......((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((((...))))))))..((((((((...))))))))..)))).......(((((((((((....)))))))))))......((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((((.)))))))))..(((((((((.)))))))))..))))......((((((((((((....)))))))))))).....((((((.....))))))......................',...
    '......((((((.....))))))...........((((...(((((((((.)))))))))..(((((((((.)))))))))..)))).....(((((((((((((....)))))))))))))....((((((.....))))))......................',...
    '......((((((.....))))))...........((((...((((((((...))))))))..((((((((...))))))))..))))....((((((((((((((....))))))))))))))...((((((.....))))))......................',...
};


design_name = {...
'S1-Ann',...
'S1-Ann-stemext1',...
'S1-Ann-stemext2',...
'S1-Ann-stemext3',...
'S1-Ann-stemext4',...
'S1-Ann-stemext5',...
'S1-Ann-stemext6',...
'S1-Ann-stemext7',...
'S7-Ann',...
'S7-Ann-stemext1',...
'S7-Ann-stemext2',...
'S7-Ann-stemext3',...
'S7-Ann-stemext4',...
'S7-Ann-stemext5',...
'S7-Ann-stemext6',...
'S7-Ann-stemext7',...
              };

for i = 1:16
    clf;
    d{i}  = d_all (:,9*(i-1) + [1:9]);
    da{i} = da_all(:,9*(i-1) + [1:9]);
    
    offset = 0;
    if ~exist( 'xsel', 'var' ) xsel = {}; end;
    if length( xsel ) < i && i > 1, xsel{i} = xsel{i-1}; end;
    if length( xsel ) < i, xsel{i} = []; end;
    
    % data analysis
    first_RT_nucleotide = length( sequence{i} ) - 20 + offset;
    [xsel{i},seqpos,area_pred{i}] = annotate_sequence( d{i}, xsel{i}, sequence{i},offset, data_type, first_RT_nucleotide, structure{i} );
    [area_peak{i},darea{i}] = fit_to_gaussians(d{i}, xsel{i});
    
    % New for HiTRACE v2.0 : standardization
    a_undil = area_peak{i};
    a_dil   = area_peak{i}; % It doesn't seem like Ann ran 'diluted' samples.
    
    error_undil = darea{i};
    error_dil   = darea{i}; % It doesn't seem like Ann ran 'diluted' samples.
    
    bkg_col = 1;
    refpos = strfind( sequence{i}, 'GAGUA' ); % 13 133
    refpos = [ refpos(1) + [0:4], refpos(2)+[0:4] ];
    [ reactivity{i}, reactivity_error{i}, seqpos_out, extra_annotations ] = get_reactivities( a_undil, a_dil, error_undil, error_dil, bkg_col, refpos, seqpos, [], data_type, sequence{i}, offset);
end

% now output standardized data.
% Save RDAT of raw data.
name = 'Triangle of Doom';
annotations = { 'chemical:Na-HEPES:50mM(pH8.0)','chemical:MgCl2:40mM','temperature:24C','experimentType:StandardState','modifier:1M7'};
comments = {'RNA was folded for 20 minutes at room temperature','Data gathered April, 2018'};
annotations_standardized = [ annotations, extra_annotations ];
for i = 1:length( reactivity )
    data_out      (:,i) = reactivity{i}(:,2);
    data_out_error(:,i) = reactivity_error{i}(:,2);
    data_annotations{i} = {['EteRNA:design_name:',design_name{i}],['sequence:',sequence{i}],['structure:',structure{i}]};    
end
goodpos = [9:143];
filename = 'POLYA_1M7_000000.rdat';
output_workspace_to_rdat_file( filename, name, sequence{1}, offset,...
    seqpos_out(goodpos), data_out(goodpos,:), structure{1}, annotations_standardized, ...
    data_annotations,data_out_error(goodpos,:),[],[],[],comments);
figure(2); clf; r = show_rdat( filename );


annotations = { 'chemical:Na-HEPES:50mM(pH8.0)','chemical:MgCl2:40mM','temperature:24C','experimentType:StandardState','modifier:DMS'};
comments = {'RNA was folded for 20 minutes at room temperature','Data gathered April, 2018'};
annotations_standardized = [ annotations, extra_annotations ];
for i = 1:length( reactivity )
    data_out      (:,i) = reactivity{i}(:,9);
    data_out_error(:,i) = reactivity_error{i}(:,9);
    data_annotations{i} = {['EteRNA:design_name:',design_name{i}],['sequence:',sequence{i}],['structure:',structure{i}]};    
end
filename = 'POLYA_DMS_000000.rdat';
output_workspace_to_rdat_file( filename, name, sequence{1}, offset,...
    seqpos_out(goodpos), data_out(goodpos,:), structure{1}, annotations_standardized, ...
    data_annotations,data_out_error(goodpos,:),[],[],[],comments);
figure(2); clf; r = show_rdat( filename );


% overlay with error bars
set( figure(10), 'Name','Plot with Error Bars','Position',[100 100 1000 600] );
clf
subplot(2,1,1);
errorbar( repmat(r.seqpos,[8,1])', r.reactivity(:,1:8), r.reactivity_error(:,1:8),'.-' )
legend( design_name(1:8) );
hold on; for i = 1:length( r.sequence ); text( i, -0.3, r.sequences{1}(i),'VerticalAlign','Bottom','HorizontalAlign','Center' ); end;
set(gca,'ylim', [-0.3,3]);

subplot(2,1,2);
errorbar( repmat(r.seqpos,[8,1])',  r.reactivity(:,9:16), r.reactivity_error(:,9:16),'.-' )
legend( design_name(9:16) );
hold on; for i = 1:length( r.sequence ); text( i, -0.3, r.sequences{9}(i),'VerticalAlign','Bottom','HorizontalAlign','Center' ); end;
set(gca,'ylim', [-0.3,3]);
set(gcf, 'PaperPositionMode','auto','color','white');

print( 'TOD_plot_traces_with_errorbars.eps', '-depsc2' );




